### ISSUE TITLE
AttributeError: type object 'int' has no attribute 'from_bytes'

### ISSUE THREAD

**Issue by luismanson** [fin-ger/logitech-m720-config#1]
Hello, im trying to use your code but i have an iisue. 
pip install was complaining to install solaar, so i got the ubuntu package and modified m720-config and added its path "sys.path.append('/usr/share/solaar/lib/')"
This did the trick but im having another issue:
```

m720-config     
Traceback (most recent call last):
  File "/home/luis/.local/bin/m720-config", line 12, in <module>
    load_entry_point('m720-config', 'console_scripts', 'm720-config')()
  File "/tmp/logitech-m720-config-master/m720_config/__init__.py", line 150, in main
    cids = print_cid_info (buttons)
  File "/tmp/logitech-m720-config-master/m720_config/__init__.py", line 124, in print_cid_info
    cnt = buttons.get_count ()
  File "/tmp/logitech-m720-config-master/m720_config/__init__.py", line 43, in get_count
    return int.from_bytes (self.m720.request ((self.feature_index << 8) + (0 << 4) + self.software_id), byteorder='little')
AttributeError: type object 'int' has no attribute 'from_bytes'
```
Can you give me any tips to fix this problem? 

Just in case, the original instructions caused this error:

```Obtaining file:///tmp/logitech-m720-config-master
Collecting solaar (from m720-config==0.0.1)
  Using cached https://files.pythonhosted.org/packages/c8/c5/8940f78388854e208ed1cb04500284e304ca843a51e7de7f439fd03242df/solaar-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jmKvK1/solaar/setup.py", line 11, in <module>
        from solaar import NAME, __version__
    ImportError: No module named solaar
    
//    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jmKvK1/solaar/
```

Thanks :)

**Comment by fin-ger** [comment]
I am using [this](https://pypi.org/project/solaar/) module from the official pypi index. Are you using pip3 for installing this?

**Comment by luismanson** [comment]
Thanks, the problem was the default python version, its working now. 
I still cant figure how this works, Any chance to point me on a direction to map the button as a keyboard event?

**Comment by fin-ger** [comment]
Sorry for the late answer! Please have a look into

https://lekensteyn.nl/files/logitech/x1b04_specialkeysmsebuttons.html#setCidReporting

for the setCidReporting function. This enables you to remap the function of a physical button on your mouse to the function of another button on the same mouse. I dont know whether it is possible to map it to a keyboard event, but you can try it!

For an example please have a look at https://github.com/fin-ger/logitech-m720-config/blob/fe7ee7dfa65e0024e71eca668fde46c237579c2b/m720_config/__init__.py#L155

**Comment by i-need-to-tell-you-something** [comment]
> I am using [this](https://pypi.org/project/solaar/) module from the official pypi index. Are you using pip3 for installing this?

Should I be using pip3? Sorry, I didn't get it.

How do I change my default Python? I tried alias, but that still returned the same above mentioned error (`No module named solaar`).

**Comment by fin-ger** [comment]
Hmm... I got the error reproduced in an ubuntu docker container and it looks like ubuntu is messing around with the python library paths... I am looking into a fix right now.

**Comment by i-need-to-tell-you-something** [comment]
I'd be satisfied with even a workaround in an accessible format (README.md or here in the issues). Also thanks for the super-speedy response!

**Comment by fin-ger** [comment]
So this is an installation issue of solaar itself and not related to my script. I was not able to get it working under ubuntu. Also, when installing solaar via apt-get, the library is not found by python.

Tbh I am sick of dependencies not working in python and may reimplement this in another language when I have some time. The code itself is trivial...

You can check whether installing `solaar` via apt-get and placing

```python
import sys
sys.path.append('/usr/share/solaar/lib/')
```

at the top of `__init__.py` will work for you. However, you may have to manually install missing dependencies of solaar with `pip3`.

**Comment by fin-ger** [comment]
Okay, I got it working with an ugly workaround:

```
$ PYTHONPATH="./lib" pip3 install --user -e .
$ pip3 install --user pyudev
```

I added instructions to the readme. This worked for me in an ubuntu docker container.

**Comment by fin-ger** [comment]
Please reopen if the issue persists
