### ISSUE TITLE
Anyone here has a problem on switching back and forth between computers?

### ISSUE THREAD

**Issue by lattice0** [fin-ger/logitech-m720-config#12]
On Ubuntu I always have to manually reconnect M720 but not my logitech K380. Anyone has this? Any solutions?

**Comment by fin-ger** [comment]
This issue tracker is specific to the configuration script of this repository and not for general problems with Logitech products. Actually, I will most likely be the only one reading this and for me this is working fine. However, I'm also not using Ubuntu but Fedora. You might be better of asking on Reddit or any other forum platform. You might also ask the Logitech Support.
