### ISSUE TITLE
Installation/utilization unclear

### ISSUE THREAD

**Issue by Amathadius** [fin-ger/logitech-m720-config#2]
Would you please be a little clearer and more specific about the installation/utilization of this script?

Where is m720-config?

```
Installing collected packages: m720-config
  Running setup.py develop for m720-config
Successfully installed m720-config
$ m720-config
zsh: command not found: m720-config
```

**Comment by fin-ger** [comment]
The script is installed to `~/.local/bin` by `pip`. In order to run it `~/.local/bin` must be in your `PATH` variable. Does this help? I also adjusted the README.

Thanks for your feedback :thumbsup:

**Comment by Amathadius** [comment]
Yes, it helps. Thank you.
