### ISSUE TITLE
Configuration is not working when connected over Bluetooth

### ISSUE THREAD

**Issue by ltachev** [fin-ger/logitech-m720-config#4]
Hi, trying this on Manjaro/Arch and it fails with the following output
```
[ltachev@enterprise logitech-m720-config]$ m720-config 
Traceback (most recent call last):
  File "/home/ltachev/.local/bin/m720-config", line 11, in <module>
    load_entry_point('m720-config', 'console_scripts', 'm720-config')()
  File "/home/ltachev/logitech-m720-config/m720_config/__init__.py", line 149, in main
    buttons = SpecialKeysMseButtons ()
  File "/home/ltachev/logitech-m720-config/m720_config/__init__.py", line 25, in __init__
    device_info = next (r for r in receivers () if r.product_id == "c52b")
StopIteration
```
Mouse is paired via Bluetooth. 
Does your script only work when paired with the Logitech receiver ??
 thanks.

**Comment by fin-ger** [comment]
Yes, I think so. I am currently only looking for a mouse on connected receivers.

The bluetooth vendor ID for this mouse is `046d` and the product ID is `b015`. You might get it working by checking the [solaar](https://github.com/pwr-Solaar/Solaar/tree/master/lib) source code for a bluetooth API.

I don't know whether it is possible to do it over Bluetooth or not :cry:

When you have a solution I am happy to integrate it into my code!

**Comment by HuangLiPang** [comment]
same issue here
but still a great work

**Comment by fin-ger** [comment]
Unfortunately it's not possible with my script to configure a mouse over bluetooth. I am using Solaar for interfacing with the mouse and Solaar does not support bluetooth :disappointed: 

> Solaar does not work with Logitech peripherals that use Bluetooth or peripherals from other companies.
> -- Solaar README

However, as of [March 22nd 2020](https://github.com/libratbag/libratbag/commit/5b23c9ebae60d9374b9ef36877264346d8255a7c) [`libratbag`](https://github.com/libratbag/libratbag) has basic support for the Logitech M720 and [Piper](https://github.com/libratbag/piper) got support for the M720 on [April 2nd 2020](https://github.com/libratbag/piper/commit/964e229343cd603efa34cb85bd4bed9c3ccaeb7f). Bluetooth devices **should** be configurable with Piper. However, my tests revealed it's a bit unstable for now and the changes are not part of any release, yet. You will have to build the software from source.
