### ISSUE TITLE
How to undo changes

### ISSUE THREAD

**Issue by hannonq** [fin-ger/logitech-m720-config#5]
Hi, thanks for the great script.  

I've ran it with the defaults for testing purposes, but that's not what I wanted to keep forever. 
Now both buttons 0x53 and 0xD0 work as "back" button.

I've tried to reset my thumb button to not doing anything like before by changing the code to `buttons.set_cid_reporting (0x53, False, False, True, True, False, False, 0x53)`, but that doesn't seem to work.

How can I undo the changes?

Thanks!

**Comment by fin-ger** [comment]
Turn off your mouse and unplug the Logitech Unifying Receiver from USB. After pluggin the receiver back in and turning on your mouse, all changes will be set to defaults.

**Comment by hannonq** [comment]
Ah, I didn't know that they were non-persistent changes. Thanks!

By any chance, do you know if it's also possible to map the buttons to other system functions? I'm particularly interested in mapping the thumb button to the "mission control". That applications overview you get on Gnome Shell when pressing the keyboard supper key.

If it's possible and you can point me to where to look for it, I can probably get it to work myself.

**Comment by fin-ger** [comment]
This is possible with [Piper](https://github.com/libratbag/piper). But last time I checked, the M720 was still missing support. Maybe it is working now, but it is definitely planned by the authors to fully support the M720 in the future.

**Comment by hannonq** [comment]
Alright, I'll check it out. Thanks a lot!
